deploy_composer_tag:
  only:
    - tags
  stage: deploy
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${COMPOSER_DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"

deploy_composer_branch:
  only:
    - push
  stage: deploy
  script:
    - curl -sS --show-error --fail --data branch=${CI_COMMIT_REF_NAME} "https://__token__:${COMPOSER_DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
