stages:
  - test
  - deploy

deploy_composer_tag:
  stage: deploy
  only:
    - tags
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${COMPOSER_DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"

deploy_composer_branch:
  stage: deploy
  only:
    - branches
  script:
    - curl -sS --show-error --fail --data branch=${CI_COMMIT_REF_NAME} "https://__token__:${COMPOSER_DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"

test:
  stage: test
  only:
    - branches
  image: redbitcz/gitlab-ci-php:7.4
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
  script:
    - composer install
    - php -d memory_limit=512M vendor/bin/phpstan analyse src/ --level 6
