stages:
  - install
  - tests
  - deploy

install:
  stage: install
  only:
    - branches
  image: redbitcz/gitlab-ci-php:7.4
  cache:
    key:
      files:
        - composer.json
      prefix: ${CI_COMMIT_REF_SLUG}
    paths:
      - composer.lock
      - vendor/
  artifacts:
    untracked: true
    paths:
      - vendor/
  script:
    - composer install --optimize-autoloader

tests:phpstan:
  stage: tests
  only:
    - branches
  image: redbitcz/gitlab-ci-php:7.4
  dependencies:
    - install
  script:
    - php -d memory_limit=512M vendor/bin/phpstan analyse src/ tests/ --level 6

tests:nette_tester:
  stage: tests
  only:
    - branches
  image: redbitcz/gitlab-ci-php:7.4
  dependencies:
    - install
  script:
    - php -d memory_limit=512M vendor/bin/tester tests/ -s

deploy:composer:tag:
  stage: deploy
  only:
    - tags
  script:
    - curl -fsS -u "__token__:${COMPOSER_PACKAGE_BUILDER_TOKEN}" --data "tag=${CI_COMMIT_TAG}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/composer"

deploy:composer:branch:
  stage: deploy
  only:
    - branches
  script:
    - curl -fsS -u "__token__:${COMPOSER_PACKAGE_BUILDER_TOKEN}" --data "branch=${CI_COMMIT_REF_NAME}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/composer"
